{{- if .Values.mtls.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: stellar-node-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stellar-operator
    app.kubernetes.io/component: security
spec:
  selector:
    matchLabels:
      stellar.org/mtls-mode: strict
  mtls:
    mode: STRICT
{{- end }}