#!/usr/bin/env python3
# Copyright 2024 Stellar-K8s Contributors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate compliant instrumentation from the observability contract schema.

Issue #1481. Writes a Rust module that emits logs/metrics/traces with the
canonical resource-attribute set derived from pod identity.

Usage:
    python3 scripts/generate-observability-instrumentation.py \\
        --service stellar-golden-path \\
        --out generated/observability_instrumentation.rs
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA = REPO_ROOT / "schemas" / "observability" / "resource-attributes.v1.json"


def render(service: str, schema: dict) -> str:
    version = schema.get("contractVersion", "1.0.0")
    required = schema.get("required") or []
    ident = service.replace("-", "_")
    required_lits = ", ".join(f'"{k}"' for k in required)
    return f"""// Generated by scripts/generate-observability-instrumentation.py
// Contract version {version}. Do not add resource attributes that are not
// listed in schemas/observability/resource-attributes.v1.json.

use stellar_k8s::observability_contract::{{
    emit_golden_path_signals, PodIdentity, SignalEnvelope, CONTRACT_VERSION,
    CONTRACT_VERSION_KEY,
}};

pub const GENERATED_SERVICE_NAME: &str = "{service}";
pub const GENERATED_CONTRACT_VERSION: &str = "{version}";
pub const REQUIRED_RESOURCE_KEYS: &[&str] = &[{required_lits}];

pub fn emit_{ident}_telemetry() -> Vec<SignalEnvelope> {{
    std::env::set_var("OTEL_SERVICE_NAME", GENERATED_SERVICE_NAME);
    let identity = PodIdentity::from_env();
    let signals = emit_golden_path_signals(&identity);
    for signal in &signals {{
        assert_eq!(
            signal.resource.get(CONTRACT_VERSION_KEY).map(String::as_str),
            Some(CONTRACT_VERSION)
        );
        for key in REQUIRED_RESOURCE_KEYS {{
            assert!(
                signal.resource.contains_key(*key),
                "generated instrumentation missing {{key}}"
            );
        }}
    }}
    signals
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--service", default="stellar-golden-path")
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "generated" / "observability_instrumentation.rs",
    )
    parser.add_argument("--schema", type=Path, default=SCHEMA)
    args = parser.parse_args(argv)
    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    text = render(args.service, schema)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} (contract {schema.get('contractVersion')})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
